`timescale 1ns / 1ps
//========================================================================
// memmap.v - the Корвет's memory-configuration PLM (КР556РТ2, D31).
//
// GENERATED by tools/decplm.py --verilog (make memmap) - do not edit.
// The equations are the PLM's fuse map as Славик redrew it for the 2022
// board's EPM3032 (infosource/ПЛМ_v1.zip, D31.v), on the pins MAME's
// pk8020.cpp feeds the same map through: the top eight address bits,
// the five system-register bits (port 7Fh, bits 2..6), the read strobe
// on input 15 and the write strobe on input 13.  tools/decplm.py checks
// them against Emu80's mapper.mem on every read of every configuration.
//
// The outputs, active low but for the top pair:
//   z[0] ROM3 (4000h-5FFFh)   z[1] the keyboard   z[2] ROM1   z[3] ROM2
//   z[4] the device page      z[5] the system-register page (writes)
//   z[7:6] 00 RAM, 01 the graphics RAM, 10 the text RAM, 11 nothing
// A read under a ROM window gives the ROM and no RAM; a write there
// gives the RAM under it.  The keyboard and register pages read as RAM
// where the PLM says so, and Emu80 says 0FFh; platform.md has the table.
//========================================================================
module memmap (
    input  [15:8] a,        // the address, top byte
    input  [6:2]  sr,       // the system register, port 7Fh bits 6..2
    input         rd,
    input         wr,
    output [7:0]  z
);

assign z[0] = ~(rd&1'b1&~sr[2]&sr[6]&~sr[3]&~a[13]&~a[15]&a[14]);

assign z[1] = ~((1'b1&~wr&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~wr&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~wr&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14]));

assign z[2] = ~((rd&1'b1&~sr[2]&~a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[3]&~a[13]&~a[15]&~a[14]));

assign z[3] = ~((rd&1'b1&~sr[2]&~sr[6]&~sr[4]&~a[12]&~sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[11]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&sr[6]&a[13]&~a[15]&~a[14]));

assign z[4] = ~((1'b0)|(1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14]));

assign z[5] = ~((~rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(~rd&1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&~a[14])|(~rd&1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b0));

assign z[6] = (1'b0)|(1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~wr&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~wr&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~wr&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(~rd&1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&~a[14])|(~rd&1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b0)|(1'b1&sr[5]&sr[6]&a[15]&a[14])|(1'b1&sr[5]&~sr[6]&sr[4]&~a[15]&a[14])|(1'b1&sr[5]&~sr[4]&a[15]&a[14])|(rd&1'b1&~sr[2]&~a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[3]&~a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&~sr[4]&~a[12]&~sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[11]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&sr[6]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&sr[6]&~sr[3]&~a[13]&~a[15]&a[14]);

assign z[7] = (1'b0)|(1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~wr&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[9]&a[11]&~a[15]&~a[10]&~a[14])|(1'b1&~wr&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14])|(1'b1&~wr&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[8]&a[9]&a[11]&~a[15]&~a[10]&~a[14])|(~rd&1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&~a[8]&a[9]&a[11]&a[15]&~a[10]&a[14])|(~rd&1'b1&sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&~a[14])|(~rd&1'b1&sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b1&~sr[5]&sr[6]&sr[4]&a[12]&a[13]&a[8]&a[9]&a[11]&a[15]&a[10]&a[14])|(1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&a[11]&~a[15]&a[10]&~a[14])|(1'b1&~sr[5]&~sr[6]&sr[4]&a[12]&a[13]&a[11]&a[15]&a[10]&a[14])|(1'b1&~sr[5]&sr[6]&~sr[4]&a[12]&a[13]&a[11]&a[15]&a[10]&a[14])|(~rd&1'b0)|(rd&1'b1&~sr[2]&~a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[3]&~a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&~sr[4]&~a[12]&~sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&~sr[4]&a[12]&~sr[3]&a[13]&~a[11]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&~sr[6]&sr[3]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&sr[6]&a[13]&~a[15]&~a[14])|(rd&1'b1&~sr[2]&sr[6]&~sr[3]&~a[13]&~a[15]&a[14]);

endmodule
