//========================================================================
// Behavioural models of what Verilator cannot read, for simulation only.
//========================================================================
// Four modules of the design are nothing but Gowin primitives:
//   src/sys_pll.v            an rPLL
//   src/hdmi/hdmi_serdes.v   an rPLL, four OSER10s, four ELVDS_OBUFs
//   src/korvet/opts_rom.v    twelve pROMs, generated by tools/bin2prom.py
//   src/korvet/font_rom.v    four pROMs, the same
// tools/srcs.py lists them as STUBBED and the flows take these instead.
// Each matches its counterpart's port list exactly and quotes the
// parameters it stands in for, so a change there can be checked here.
//========================================================================
`timescale 1ns / 1ps

//------------------------------------------------------------------------
// sys_pll - src/sys_pll.v
//   IDIV_SEL 1, FBDIV_SEL 2 => clkout = clkin * 3 / 2 = 40.5 MHz from 27
//   PSDA_SEL "0100"         => clkoutp 90 degrees behind
// The input period is measured rather than assumed, so a testbench that
// clocks something other than 27 MHz still gets the right ratio.
//------------------------------------------------------------------------
module sys_pll (
    input       clkin,
    output      clkout,
    output      clkoutp,
    output reg  lock
);
    parameter IDIV  = 2;
    parameter FBDIV = 3;
    parameter PSDA  = 4;

    real tin  = 0.0;
    real tout = 0.0;
    time prev = 0;

    reg clkout_r  = 1'b0;
    reg clkoutp_r = 1'b0;
    assign clkout  = clkout_r;
    assign clkoutp = clkoutp_r;

    initial lock = 1'b0;

    always @(posedge clkin) begin
        if (prev != 0 && tin == 0.0) begin
            tin  = $realtime - prev;
            tout = tin * IDIV / FBDIV;
        end
        prev = $realtime;
    end

    initial begin
        wait (tout > 0.0);
        #(tout * 3);
        lock = 1'b1;
    end

    initial begin
        wait (tout > 0.0);
        forever #(tout / 2.0) clkout_r = ~clkout_r;
    end

    initial begin
        wait (tout > 0.0);
        #(tout * PSDA / 16.0);
        forever #(tout / 2.0) clkoutp_r = ~clkoutp_r;
    end
endmodule

//------------------------------------------------------------------------
// hdmi_serdes - src/hdmi/hdmi_serdes.v.  The pads are tied off; the
// checking happens one level up, on the ten-bit TMDS words, which
// sim/tb/tb_top.v decodes back into pixels and packets.
//------------------------------------------------------------------------
module hdmi_serdes (
    input        clk_pixel,
    input        ref_locked,
    input  [9:0] tmds_ch0,
    input  [9:0] tmds_ch1,
    input  [9:0] tmds_ch2,
    output       O_tmds_clk_p,
    output       O_tmds_clk_n,
    output [2:0] O_tmds_data_p,
    output [2:0] O_tmds_data_n
);
    assign O_tmds_clk_p  = 1'b0;
    assign O_tmds_clk_n  = 1'b1;
    assign O_tmds_data_p = 3'b000;
    assign O_tmds_data_n = 3'b111;
endmodule

//------------------------------------------------------------------------
// opts_rom - src/korvet/opts_rom.v: 12288 x 16, registered, the image
// out of tang/rom/korvet20.rom through mif.py binhex (little-endian
// words, as bin2prom.py packs them).  +OPTS_HEX=<file> reads another
// image, the same way (make sim ROM=tang/rom/korvet11.rom).
//------------------------------------------------------------------------
module opts_rom (
    output reg [15:0] dout,
    input             clk,
    input             ce,
    input             reset,
    input      [13:0] ad
);
    parameter MEM_HEX = "build/mif/opts_rom.hex";
    reg [15:0] mem [0:16383];
    reg [1023:0] fname;
    integer i;
    initial begin
        for (i = 0; i < 16384; i = i + 1) mem[i] = 16'h0000;
        if ($value$plusargs("OPTS_HEX=%s", fname)) $readmemh(fname, mem);
        else $readmemh(MEM_HEX, mem);
        dout = 16'h0000;
    end
    always @(posedge clk)
        if (reset)   dout <= 16'h0000;
        else if (ce) dout <= mem[ad];
endmodule

//------------------------------------------------------------------------
// font_rom - src/korvet/font_rom.v: 4096 x 16, the character generator
// out of tang/rom/korvet2.fnt.
//------------------------------------------------------------------------
module font_rom (
    output reg [15:0] dout,
    input             clk,
    input             ce,
    input             reset,
    input      [11:0] ad
);
    parameter MEM_HEX = "build/mif/font_rom.hex";
    reg [15:0] mem [0:4095];
    integer i;
    initial begin
        for (i = 0; i < 4096; i = i + 1) mem[i] = 16'h0000;
        $readmemh(MEM_HEX, mem);
        dout = 16'h0000;
    end
    always @(posedge clk)
        if (reset)   dout <= 16'h0000;
        else if (ce) dout <= mem[ad];
endmodule
