# Generated by tools/gowin_tcl.py - do not edit, regenerate.
# Run from the tang/ directory:  gw_sh build.tcl

set_device -name GW2AR-18C GW2AR-LV18QN88C8/I7

add_file -type verilog "src/top.v"
add_file -type verilog "src/sys_pll.v"
add_file -type verilog "src/i2s_tx.v"
add_file -type verilog "src/korvet/vm80a.v"
add_file -type verilog "src/korvet/cpu8080.v"
add_file -type verilog "src/korvet/tv80_core.v"
add_file -type verilog "src/korvet/tv80_alu.v"
add_file -type verilog "src/korvet/tv80_mcode.v"
add_file -type verilog "src/korvet/tv80_reg.v"
add_file -type verilog "src/korvet/cpuz80.v"
add_file -type verilog "src/korvet/memmap.v"
add_file -type verilog "src/korvet/membus.v"
add_file -type verilog "src/korvet/sdram.v"
add_file -type verilog "src/korvet/memcheck.v"
add_file -type verilog "src/korvet/opts_rom.v"
add_file -type verilog "src/korvet/font_rom.v"
add_file -type verilog "src/korvet/romload.v"
add_file -type verilog "src/korvet/txtram.v"
add_file -type verilog "src/korvet/video.v"
add_file -type verilog "src/korvet/ports.v"
add_file -type verilog "src/korvet/devices.v"
add_file -type verilog "src/korvet/ppi8255.v"
add_file -type verilog "src/korvet/pit8253.v"
add_file -type verilog "src/korvet/pic8259.v"
add_file -type verilog "src/korvet/i8251.v"
add_file -type verilog "src/korvet/mouse.v"
add_file -type verilog "src/korvet/fdc.v"
add_file -type verilog "src/korvet/wd1793.sv"
add_file -type verilog "src/korvet/ay.v"
add_file -type verilog "src/korvet/ym2149.sv"
add_file -type verilog "src/korvet/extrom.v"
add_file -type verilog "src/korvet/sd_arbiter.v"
add_file -type verilog "src/korvet/poke.v"
add_file -type verilog "src/hdmi/hdmi_packet.v"
add_file -type verilog "src/hdmi/hdmi_serdes.v"
add_file -type verilog "src/hdmi/hdmi_tx.v"
add_file -type verilog "src/hdmi/tmds_channel.v"
add_file -type verilog "src/mister/hid.v"
add_file -type verilog "src/mister/mcu_spi.v"
add_file -type verilog "src/mister/osd_u8g2.v"
add_file -type verilog "src/mister/sd_card.v"
add_file -type verilog "src/mister/sd_rw.v"
add_file -type verilog "src/mister/sdcmd_ctrl.v"
add_file -type verilog "src/mister/sector_dpram.v"
add_file -type verilog "src/mister/sysctrl.v"
add_file -type cst "src/korvet.cst"
add_file -type sdc "src/korvet.sdc"

set_option -top_module top
set_option -verilog_std sysv2017
set_option -global_freq 100.000
set_option -rw_check_on_ram 0
set_option -use_sspi_as_gpio 1
set_option -correct_hold_violation 1
set_option -output_base_name korvet

run all
